In [2]:
import pickle
import glob
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
import lightgbm as lgb
from sklearn.metrics import f1_score
# import time
# print('sleeping')
# time.sleep(7200)
# print('sleep done =======================')
# load feats
y_preds_all = []
y_trues_all = []
y_test_preds_all = []
for feat in sorted(glob.glob('../feature/bagging/*')):
    print('file path',feat)
    a,b,c = pickle.load(open(feat,'rb'))
    print(a.shape,b.shape)
    y_preds_all.append(a)
    y_trues_all.append(b)
    y_test_preds_all.append(c)
# load y
train = pd.read_csv("../input/new_data/train_set.csv")
# list_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]
# train_y = train[list_classes].values.astype('int')
# print(train_x.shape)

file path ../feature/bagging/rnn_model_bagging1.pkl
(56590, 19) (56590, 19)
file path ../feature/bagging/rnn_model_bagging2.pkl
(56590, 19) (56590, 19)
file path ../feature/bagging/rnn_model_bagging3.pkl
(56590, 19) (56590, 19)


In [3]:
np.corrcoef(y_preds_all[0][:,0], y_preds_all[1][:,0])

array([[1.        , 0.93459933],
       [0.93459933, 1.        ]])

In [43]:
# y = y_trues_all[0]
y[:,5].shape

(56590,)

In [5]:
np.array(y_preds_all)

array([[[1.8630869e-08, 2.9356926e-07, 2.1145908e-07, ...,
         3.4839523e-08, 1.1018854e-04, 9.9985576e-01],
        [2.4553029e-02, 5.2418782e-06, 2.2986982e-04, ...,
         4.5884890e-04, 2.3034238e-05, 2.9243096e-05],
        [3.3866694e-08, 1.0681297e-11, 9.9990904e-01, ...,
         7.8480855e-10, 1.1327355e-07, 8.7279702e-08],
        ...,
        [4.5157832e-04, 4.2930693e-05, 5.5644205e-03, ...,
         3.3414379e-02, 1.3150198e-03, 1.0587270e-02],
        [8.4539055e-04, 1.5751001e-03, 1.5836615e-02, ...,
         7.9410546e-04, 5.4711738e-04, 1.3594753e-01],
        [1.3048108e-01, 3.6731706e-04, 7.2827017e-05, ...,
         6.3033903e-04, 5.6701113e-04, 1.5297865e-03]],

       [[1.8210084e-06, 7.8562034e-06, 1.9555974e-04, ...,
         1.2859799e-05, 1.1062146e-04, 9.9814069e-01],
        [1.7167586e-01, 1.5972940e-04, 1.5574525e-03, ...,
         1.0878749e-02, 1.4222388e-03, 1.3451822e-03],
        [1.5446903e-07, 3.6922784e-10, 9.9768639e-01, ...,
         5.399

In [6]:
from scipy.stats import gmean, hmean

preds_mean = gmean(np.array(y_preds_all) , axis=0)
# print(roc_auc_score(y_trues_all[0], preds_mean))
test_preds_mean = gmean(np.array(y_test_preds_all), axis=0)

In [7]:
preds_mean

array([[1.2161289e-06, 3.9266970e-06, 1.4805765e-05, ..., 2.4074050e-06,
        2.1898779e-04, 9.9829900e-01],
       [4.7133941e-02, 2.8934423e-05, 4.5251148e-04, ..., 2.4724260e-03,
        1.5939391e-04, 3.4292438e-04],
       [9.2532900e-08, 1.1125236e-10, 9.9903888e-01, ..., 2.3531661e-09,
        6.7025752e-07, 3.7445923e-07],
       ...,
       [4.7558622e-04, 7.0500128e-06, 6.0218368e-05, ..., 5.0377231e-03,
        2.0820987e-04, 8.1735931e-04],
       [6.8229716e-04, 6.1266182e-04, 1.0815197e-02, ..., 4.7289432e-04,
        1.8617201e-04, 1.9766283e-01],
       [8.2947217e-02, 5.5450371e-05, 4.7187077e-05, ..., 4.1734509e-04,
        5.2362605e-04, 2.5443881e-04]], dtype=float32)

In [12]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmer.stem("mother")

'mother'

In [13]:
preds_stacked = np.concatenate(np.array(y_preds_all), axis=1)
test_preds_stacked = np.concatenate(np.array(y_test_preds_all), axis=1)

In [44]:
import lightgbm as lgb
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
cvlist = list(StratifiedKFold(10,random_state=1).split(preds_stacked, y[:,5]))
y_preds2 = np.zeros((preds_stacked.shape[0], 19))

y_test_preds2 = np.zeros((test_preds_stacked.shape[0], 19))

In [46]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import roc_auc_score
for i, col in enumerate(range(19)):
    y_tmp = y[:, i]
    model = lgb.LGBMClassifier(n_estimators=100, num_leaves=8, learning_rate=0.1, min_child_samples=500,
                               subsample=0.9, colsample_bytree=0.8, reg_lambda=1.0, class_weight='balanced')

    y_preds2[:, i] = cross_val_predict(model, preds_stacked, y_tmp, cv=cvlist, n_jobs=1, method='predict_proba')[:,1]

    y_test_preds2[:, i] = model.fit(preds_stacked, y_tmp).predict_proba(test_preds_stacked)[:,1]
    print("Score for class {} is {}".format(col, roc_auc_score(y_tmp, y_preds2[:, i])))
print("Over auc score", roc_auc_score(y, y_preds2))

Score for class 0 is 0.97282088051057
Score for class 1 is 0.9881714882493464
Score for class 2 is 0.9901577025569563
Score for class 3 is 0.9920279197003412
Score for class 4 is 0.9853334765061417
Score for class 5 is 0.992407591520911
Score for class 6 is 0.9769423843338143
Score for class 7 is 0.9792017033469735
Score for class 8 is 0.9953281842417061
Score for class 9 is 0.9722154430043937
Score for class 10 is 0.9769806318659203
Score for class 11 is 0.9675512389958606
Score for class 12 is 0.9822447845567661
Score for class 13 is 0.9889765594246825
Score for class 14 is 0.9928519344637105
Score for class 15 is 0.9941799784902019
Score for class 16 is 0.9885119118485288
Score for class 17 is 0.9903284240940756
Score for class 18 is 0.9767356713761584
Over auc score 0.9843667320572137


In [48]:
y_test_preds2.shape

(102277, 19)

In [50]:
test_dir = '../input/new_data/test_set.csv'
test = pd.read_csv(test_dir)
test_id = test[["id"]].copy()

In [51]:
preds=np.argmax(y_test_preds2,axis=1)
test_pred=pd.DataFrame(preds)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]+1).astype(int)
print(test_pred.shape)
print(test_id.shape)
test_pred["id"]=list(test_id["id"])
test_pred[["id","class"]].to_csv('../output/bagging1.csv',index=None)

(102277, 1)
(102277, 1)


In [53]:
y_test_preds2

array([[0.04303668, 0.01117231, 0.0170423 , ..., 0.00496908, 0.00838028,
        0.00225438],
       [0.06548195, 0.0014784 , 0.00338679, ..., 0.00075571, 0.00224275,
        0.00674224],
       [0.38615825, 0.03139946, 0.74362352, ..., 0.05014074, 0.05240256,
        0.13416665],
       ...,
       [0.0063093 , 0.0098516 , 0.0433223 , ..., 0.00964546, 0.00335754,
        0.00421889],
       [0.0432166 , 0.00399892, 0.00158078, ..., 0.01072805, 0.02863514,
        0.01042397],
       [0.04911343, 0.02557771, 0.01572509, ..., 0.03253119, 0.00780603,
        0.05665865]])

In [55]:
test_prob=pd.DataFrame(y_test_preds2)
test_prob.columns=["class_prob_%s"%i for i in range(1,20)]
test_prob["id"]=list(test_id["id"])
test_prob.to_csv('../pro/prob_bagging.csv',index=None)

In [56]:
test_prob

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0           0.043037      0.011172      0.017042      0.051765      0.996012   
1           0.065482      0.001478      0.003387      0.997935      0.001667   
2           0.386158      0.031399      0.743624      0.130455      0.159000   
3           0.011062      0.001072      0.001093      0.998824      0.001892   
4           0.043805      0.016331      0.047437      0.129443      0.994246   
5           0.562552      0.060902      0.203231      0.010187      0.993896   
6           0.158500      0.013648      0.060306      0.060035      0.000833   
7           0.278018      0.930272      0.109379      0.044373      0.047481   
8           0.001063      0.000324      0.998962      0.000769      0.001922   
9           0.473034      0.072376      0.010996      0.030563      0.098622   
10          0.297695      0.021984      0.006869      0.002729      0.036060   
11          0.895919      0.907821      0.246165      0.030831      0.030803   
12          0.089435      0.003444      0.004345      0.001147      0.998613   
13          0.061925      0.012470      0.015488      0.104753      0.030161   
14          0.000563      0.000538      0.000466      0.000782      0.000812   
15          0.037242      0.008368      0.000535      0.000422      0.000333   
16          0.000677      0.000495      0.000714      0.000501      0.000726   
17          0.000684      0.000554      0.004365      0.000569      0.000908   
18          0.028521      0.006288      0.903207      0.041423      0.116885   
19          0.006384      0.008192      0.002919      0.003661      0.000650   
20          0.000635      0.000577      0.000699      0.000501      0.000789   
21          0.479132      0.009674      0.265301      0.178546      0.048826   
22          0.000646      0.000497      0.001838      0.000702      0.000909   
23          0.312752      0.006205      0.017498      0.015796      0.007743   
24          0.186391      0.976083      0.080898      0.832971      0.041121   
25          0.000416      0.000356      0.003647      0.001089      0.000520   
26          0.003288      0.000535      0.892574      0.000869      0.004016   
27          0.202029      0.011799      0.047220      0.032303      0.012254   
28          0.045084      0.007838      0.012062      0.997316      0.035623   
29          0.018585      0.050081      0.025865      0.002176      0.022702   
...              ...           ...           ...           ...           ...   
102247      0.030023      0.000315      0.000634      0.000605      0.001588   
102248      0.171042      0.004054      0.003966      0.000889      0.005738   
102249      0.102086      0.008543      0.032388      0.001468      0.085619   
102250      0.007705      0.997603      0.001884      0.003850      0.152039   
102251      0.008085      0.000980      0.000677      0.000559      0.000590   
102252      0.215923      0.006973      0.005713      0.015668      0.830216   
102253      0.212134      0.097636      0.004908      0.010100      0.007552   
102254      0.237377      0.992332      0.063714      0.090205      0.199497   
102255      0.080430      0.023403      0.372601      0.168303      0.018798   
102256      0.995551      0.002673      0.040543      0.001525      0.023058   
102257      0.000553      0.000396      0.008113      0.001336      0.001850   
102258      0.049607      0.030747      0.106223      0.018191      0.020428   
102259      0.000492      0.005397      0.220225      0.000881      0.001082   
102260      0.074855      0.006410      0.007099      0.026218      0.017466   
102261      0.119292      0.182968      0.211169      0.053030      0.021239   
102262      0.044768      0.994782      0.019788      0.557749      0.133107   
102263      0.061559      0.023765      0.044258      0.042529      0.015523   
102264      0.000384      0.000366      0.000704      0.000773      0.000534   
102265  