In [58]:
import pandas as pd
import numpy as np

In [120]:
result1 = pd.read_csv('../10fold_pro/prob_rnn_baseline4.csv')#rnn model
result2 = pd.read_csv('../pro/prescore_779.csv')#lr model
result3 = pd.read_csv('../pro/prob_ridge_baseline4.csv')# ridge model
result4 = pd.read_csv('../pro/prob_lgb_baseline4.csv')# lgb model
result5 = pd.read_csv('../10fold_pro/prob_cnn_baseline.csv')# cnn model
result6 = pd.read_csv('../output/prob_fm_baseline.csv')# fm model
result7 = pd.read_csv('../10fold_pro/prob_Capsule_baseline.csv')# capsule model
result8 = pd.read_csv('../pro/prob_rnn_cnn_baseline.csv')# rnn_cnn model
# resultx = pd.read_csv('../pro/prob_lgb_baseline6.csv')
result11 = pd.read_csv('../pro/prob_rnn_shufflte.csv')# rnn shufflte model
result9 = pd.read_csv('../pro/prob_capsule_shufflte.csv')# capsult model
stacking_file = pd.read_csv('../pro/stacking_lgb7.csv')# stacking lgb model
stacking_file_nn = pd.read_csv('../pro/stacking_nn.csv')# stacking nn model
stacking_file_lr = pd.read_csv('../pro/stacking_lr.csv')# stacking lr model
baggine_1 = pd.read_csv('../pro/stacking_lgb_bagging.csv')# stacking bagging lgb model

In [1]:
# lists = ["class_prob_%s"%i for i in range(1,20)] 
# other.columns = lists
# tesxxx = other.iloc[:102277,:]
# other = other.iloc[102277:,:]
# other = other.reset_index(drop=True)
# other

In [123]:
# for i in range(1,20):
#     baggine_1["class_prob_{}".format(i)] = (baggine_1["class_prob_{}".format(i)] + baggine_1["class_prob_{}".format(i)] + baggine_2["class_prob_{}".format(i)]+baggine_3["class_prob_{}".format(i)])/4
stacking_file

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0           0.002324      0.000262      0.000628      0.003035      0.990153   
1           0.003375      0.000263      0.000294      0.993289      0.000196   
2           0.053847      0.003777      0.098880      0.002276      0.018054   
3           0.000384      0.000173      0.000253      0.992985      0.000217   
4           0.008394      0.000216      0.001770      0.004306      0.949895   
5           0.043147      0.005353      0.005847      0.001030      0.904043   
6           0.020702      0.001388      0.004777      0.006158      0.000391   
7           0.031409      0.146433      0.003577      0.001341      0.002912   
8           0.000253      0.000137      0.992676      0.000184      0.000218   
9           0.118516      0.003411      0.001823      0.002864      0.002740   
10          0.054014      0.000792      0.000701      0.000596      0.002111   
11          0.312189      0.339577      0.005114      0.001282      0.016466   
12          0.004066      0.000888      0.000317      0.000269      0.982832   
13          0.015898      0.000394      0.002017      0.001718      0.000686   
14          0.000189      0.000142      0.000164      0.000227      0.000186   
15          0.000413      0.000148      0.000195      0.000186      0.000199   
16          0.000196      0.000140      0.000192      0.000177      0.000204   
17          0.000204      0.000138      0.000244      0.000178      0.000206   
18          0.001596      0.000274      0.686756      0.002017      0.001550   
19          0.001372      0.000162      0.000392      0.001024      0.000304   
20          0.000264      0.000139      0.000208      0.000178      0.000196   
21          0.099486      0.000536      0.017506      0.004576      0.002638   
22          0.000231      0.000144      0.000231      0.000189      0.000215   
23          0.079814      0.000214      0.008556      0.000657      0.000891   
24          0.010109      0.871450      0.013761      0.018661      0.002815   
25          0.000296      0.000432      0.000468      0.000183      0.000217   
26          0.000967      0.000154      0.728799      0.000462      0.000861   
27          0.015173      0.002486      0.002210      0.000881      0.000443   
28          0.012633      0.000389      0.000396      0.936516      0.000438   
29          0.001466      0.000258      0.000446      0.000241      0.001981   
...              ...           ...           ...           ...           ...   
102247      0.013676      0.000205      0.000276      0.000378      0.000703   
102248      0.023422      0.001071      0.001945      0.000257      0.002771   
102249      0.017495      0.000208      0.000921      0.000545      0.001635   
102250      0.001039      0.988969      0.000279      0.004590      0.000824   
102251      0.000436      0.000144      0.000238      0.000189      0.000192   
102252      0.021067      0.000241      0.002995      0.002589      0.137577   
102253      0.042283      0.003829      0.001029      0.000332      0.000521   
102254      0.018888      0.895857      0.002827      0.018162      0.003828   
102255      0.023617      0.000374      0.041691      0.021228      0.001895   
102256      0.970557      0.000189      0.001807      0.000218      0.002617   
102257      0.000197      0.000151      0.000912      0.000186      0.000206   
102258      0.007951      0.001690      0.003101      0.000947      0.002439   
102259      0.000540      0.001228      0.029062      0.000399      0.000260   
102260      0.013170      0.000176      0.000871      0.005111      0.000747   
102261      0.014006      0.027094      0.036890      0.002847      0.002705   
102262      0.009468      0.878821      0.002174      0.058332      0.003715   
102263      0.006722      0.004156      0.003764      0.002262      0.003504   
102264      0.000394      0.000187      0.000364      0.000213      0.000192   
102265  

In [124]:
other.shape

(102277, 19)

In [125]:
stacking = True
nn = True

In [126]:
if stacking: 
    for i in range(1,20):
        stacking_file["class_prob_{}".format(i)] = (baggine_1["class_prob_{}".format(i)] + baggine_1["class_prob_{}".format(i)] + stacking_file_lr["class_prob_{}".format(i)] + stacking_file_lr["class_prob_{}".format(i)] + stacking_file_lr["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)] + result6["class_prob_{}".format(i)] + other["class_prob_{}".format(i)]+ stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)])/15
#         stacking_file["class_prob_{}".format(i)] = (stacking_file_lr["class_prob_{}".format(i)] + stacking_file_lr["class_prob_{}".format(i)] + stacking_file_lr["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)] + stacking_file_nn["class_prob_{}".format(i)]  + result6["class_prob_{}".format(i)] + result4["class_prob_{}".format(i)]+ stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)]+stacking_file["class_prob_{}".format(i)])/11
else:
    for i in range(1,20):
        result2["class_prob_{}".format(i)] = (result8["class_prob_{}".format(i)]+result7["class_prob_{}".format(i)] + result7["class_prob_{}".format(i)] + result6["class_prob_{}".format(i)] + result6["class_prob_{}".format(i)] + result5["class_prob_{}".format(i)] + result4["class_prob_{}".format(i)] +result3["class_prob_{}".format(i)] + result2["class_prob_{}".format(i)] + result3["class_prob_{}".format(i)] + result2["class_prob_{}".format(i)] + result1["class_prob_{}".format(i)] + result1["class_prob_{}".format(i)] + result1["class_prob_{}".format(i)])/14


In [127]:
# pred2 = result2[lists].values

In [128]:
if stacking:
    pred = stacking_file[lists].values
else:
    pred = result2[lists].values

In [129]:
# lgb7_nn_lr = pred
# lgb_nn5_lr = pred

In [130]:
# pred = (lgb7_nn_lr+lgb_nn5_lr)/2

In [131]:
pred[0]

array([0.00793863, 0.00871789, 0.01191029, 0.01864988, 0.98120621,
       0.01393073, 0.01424773, 0.01375206, 0.0111479 , 0.00352468,
       0.01752062, 0.01462758, 0.00677134, 0.01470531, 0.01187555,
       0.00869645, 0.01635133, 0.00860216, 0.01711615])

In [132]:
#这个文件是re_blend后生成的
pred2 = pd.read_csv('all_blend_file3.csv')

In [133]:
pred3 = (pred + pred2[lists].values + pred)/3

In [134]:
preds=np.argmax(pred3,axis=1)
test_pred=pd.DataFrame(preds)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]+1).astype(int)

In [135]:
test_pred["id"]=list(result2["id"])
test_pred[["id","class"]].to_csv('../blend_output/blend_and_stacking28.csv',index=None)
#这就是提交文件

In [136]:
test_pred.loc[test_pred['class']==1]

class      id
11          1      11
73          1      73
75          1      75
81          1      81
86          1      86
104         1     104
145         1     145
150         1     150
153         1     153
166         1     166
168         1     168
202         1     202
212         1     212
217         1     217
275         1     275
299         1     299
330         1     330
347         1     347
379         1     379
397         1     397
407         1     407
416         1     416
444         1     444
446         1     446
473         1     473
516         1     516
518         1     518
525         1     525
531         1     531
533         1     533
...       ...     ...
101590      1  101590
101629      1  101629
101654      1  101654
101684      1  101684
101698      1  101698
101704      1  101704
101711      1  101711
101753      1  101753
101786      1  101786
101811      1  101811
101818      1  101818
101824      1  101824
101834      1  101834
101899      1  101899
101919      1  101919
101937      1  101937
101969      1  101969
101988      1  101988
102016      1  102016
102022      1  102022
102026      1  102026
102056      1  102056
102058      1  102058
102067      1  102067
102080      1  102080
102083      1  102083
102134      1  102134
102165      1  102165
102208      1  102208
102256      1  102256

[4424 rows x 2 columns]

In [137]:
pred[1]

array([0.02509153, 0.01641603, 0.01037116, 0.96624254, 0.01267071,
       0.01550774, 0.01979713, 0.00640798, 0.01248032, 0.01121617,
       0.01034253, 0.02511869, 0.01452739, 0.01360531, 0.01535884,
       0.00850948, 0.01306687, 0.0245433 , 0.00762098])

In [56]:
pred2

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0          -0.019675     -0.009789      0.012401      0.014477      0.963447   
1           0.042362      0.015659     -0.000560      0.911613      0.003028   
2           0.038569      0.004124      0.140269      0.011617      0.024178   
3           0.018731     -0.006551      0.006771      0.999406      0.004003   
4           0.062107     -0.011277     -0.002636      0.004168      0.873048   
5           0.030175      0.013701      0.014677      0.024945      0.741271   
6           0.026198     -0.009508      0.032789      0.019371     -0.006132   
7           0.056710      0.155006      0.020941      0.016355      0.005410   
8           0.000775     -0.000108      0.962276      0.002849      0.000950   
9           0.114365      0.014872     -0.025628      0.007358     -0.009591   
10          0.093471     -0.011369     -0.001231     -0.011573     -0.009022   
11          0.287385      0.170290      0.010545      0.003739      0.035919   
12          0.065603      0.014213     -0.012945     -0.015268      0.978898   
13          0.000441      0.003845      0.036631      0.005582     -0.009041   
14         -0.015154     -0.006646     -0.009282      0.004184      0.011635   
15          0.015881     -0.001373     -0.007643     -0.011869      0.000436   
16          0.001903      0.004831      0.022402     -0.001429      0.004144   
17         -0.000420      0.000347     -0.001539     -0.002644      0.007692   
18         -0.002378      0.002788      0.488990      0.018832      0.008376   
19         -0.024843     -0.010251      0.005378     -0.021926     -0.004799   
20          0.028283     -0.001828      0.000407      0.004417      0.002186   
21          0.129371      0.001018      0.059457      0.003292      0.008379   
22         -0.035098      0.008853     -0.007629     -0.011551     -0.003424   
23          0.058740     -0.009411      0.012039      0.015708     -0.004570   
24          0.018265      0.780356      0.015299      0.033618     -0.009550   
25         -0.001434      0.034198     -0.000601     -0.001577     -0.003291   
26         -0.015619     -0.015711      0.785266     -0.009344     -0.001747   
27          0.006760      0.009716     -0.006602     -0.001229     -0.000167   
28          0.033024     -0.000445      0.000460      0.771940      0.008526   
29          0.019011     -0.018211      0.003577      0.010971      0.008901   
...              ...           ...           ...           ...           ...   
102247      0.056987      0.009712     -0.023424     -0.006699      0.035828   
102248      0.005014      0.017108      0.010695      0.017134      0.009618   
102249      0.039879      0.006873     -0.005255      0.007542      0.004163   
102250     -0.003846      0.967918     -0.004733      0.008076     -0.013637   
102251     -0.021183      0.002114     -0.004423      0.000448      0.005336   
102252      0.033684      0.011151     -0.004435      0.029522      0.197104   
102253      0.092791     -0.010388     -0.000844     -0.005214      0.000011   
102254      0.008045      0.890805     -0.001268      0.017225      0.001944   
102255      0.033653      0.000709      0.037534      0.040096      0.010378   
102256      0.982433      0.000286     -0.002449     -0.000859      0.000677   
102257      0.022753     -0.004787     -0.020687      0.001895     -0.003113   
102258     -0.014902      0.019797      0.040559     -0.003215      0.000743   
102259      0.004582      0.027292      0.019768      0.011094      0.000801   
102260      0.006182     -0.001092      0.006308      0.015199      0.004439   
102261      0.023538      0.046970      0.091082      0.021446      0.014008   
102262      0.000081      0.782776     -0.015736      0.047393     -0.013152   
102263      0.002651      0.005451      0.038995     -0.015865     -0.004845   
102264      0.001223     -0.001166      0.012389      0.001314      0.000543   
102265  

In [138]:
pred3[0]

array([-0.00126608,  0.00254895,  0.01207374,  0.01725875,  0.97528655,
        0.01049884,  0.01900916,  0.01098849,  0.00896886, -0.00796745,
        0.01596505,  0.01043905,  0.00319938,  0.01501857,  0.00844075,
        0.00423551,  0.01510523,  0.00370743,  0.01723725])

In [73]:
pred3

array([[-0.00636972, -0.00402786,  0.00623549, ...,  0.00955106,
        -0.0026798 ,  0.01106717],
       [ 0.0227269 ,  0.0095069 ,  0.00058837, ...,  0.00553731,
         0.02206939, -0.00256687],
       [ 0.04848347,  0.00581449,  0.10215938, ...,  0.01431305,
         0.00348716,  0.03324631],
       ...,
       [-0.00295449,  0.0048005 , -0.0093771 , ..., -0.00142479,
        -0.01438663, -0.00733048],
       [ 0.02172632,  0.00027543,  0.00362942, ...,  0.00752426,
         0.01418171,  0.01751812],
       [ 0.05694837,  0.00512095,  0.00059245, ...,  0.00776808,
        -0.00436348,  0.03078121]])

In [18]:
pred3[0]

array([-0.00634035, -0.00402067,  0.00626652,  0.00810724,  0.96357948,
        0.00394762,  0.01267506,  0.00543026,  0.002085  , -0.01294813,
        0.00905658,  0.0042434 , -0.00221163,  0.00778287,  0.00160149,
       -0.00146914,  0.0095476 , -0.00267142,  0.01104245])

In [148]:
pred[0]

array([ 1.00357901e-03, -1.23642143e-03,  3.46032600e-03,  5.89808512e-03,
        9.61321380e-01,  4.31298360e-03,  5.13926155e-03,  6.11006617e-03,
        9.27601870e-04, -3.75417719e-03,  7.60516999e-03,  5.88710083e-03,
       -1.49447010e-03,  4.12608149e-03,  1.73696346e-03,  1.66105927e-04,
        8.53432127e-03, -1.00340357e-03,  8.38581545e-03])

In [76]:
test_pred

class      id
0           5       0
1           4       1
2          13       2
3           4       3
4           5       4
5           5       5
6          15       6
7          19       7
8           3       8
9          12       9
10         10      10
11          1      11
12          5      12
13         13      13
14         15      14
15         18      15
16          9      16
17          9      17
18          3      18
19         14      19
20          9      20
21         11      21
22          9      22
23          9      23
24          2      24
25         15      25
26          3      26
27         15      27
28          4      28
29         19      29
...       ...     ...
102247     16  102247
102248      8  102248
102249     10  102249
102250      2  102250
102251     18  102251
102252     16  102252
102253     18  102253
102254      2  102254
102255     14  102255
102256      1  102256
102257      6  102257
102258     12  102258
102259     15  102259
102260     14  102260
102261     19  102261
102262      2  102262
102263     12  102263
102264     15  102264
102265     14  102265
102266     10  102266
102267      3  102267
102268      8  102268
102269     14  102269
102270      6  102270
102271     15  102271
102272      8  102272
102273      7  102273
102274      6  102274
102275     14  102275
102276     13  102276

[102277 rows x 2 columns]

In [45]:
import pickle
a,b = pickle.load(open('../feature/2leve_lgb_stacking4.pkl','rb'))

In [47]:
b[0]

array([2.01770598e-03, 2.42129618e-04, 5.36134821e-04, 2.52675895e-03,
       9.90239443e-01, 1.22651811e-03, 3.12860659e-04, 1.33844144e-04,
       2.76055685e-04, 3.25080945e-04, 1.87835989e-03, 9.36337002e-04,
       5.72086046e-04, 7.32801337e-04, 2.35359875e-04, 8.80356411e-05,
       2.15823371e-04, 2.21896168e-04, 0.00000000e+00])

In [50]:
name = ["class_prob_%s"%i for i in range(1,20)]
df_lgb = pd.DataFrame(b, columns=name)
# df_lgb = df_lgb.drop('class_prob_20', axis=1)

In [51]:
df_lgb

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0           0.002018      0.000242      0.000536      0.002527      0.990239   
1           0.002991      0.000182      0.000276      0.994518      0.000205   
2           0.053785      0.004310      0.093329      0.002444      0.018166   
3           0.000293      0.000124      0.000262      0.994762      0.000240   
4           0.008771      0.000176      0.001668      0.003347      0.952281   
5           0.044025      0.005305      0.005147      0.000871      0.900697   
6           0.019613      0.001315      0.004219      0.005277      0.000436   
7           0.029660      0.149844      0.003744      0.001113      0.002974   
8           0.000265      0.000105      0.992384      0.000109      0.000224   
9           0.114241      0.003272      0.002220      0.002787      0.002842   
10          0.058811      0.000740      0.000745      0.000544      0.001844   
11          0.302877      0.333235      0.005866      0.001195      0.017607   
12          0.004195      0.000639      0.000331      0.000227      0.982487   
13          0.017829      0.000354      0.002011      0.001694      0.000748   
14          0.000172      0.000112      0.000179      0.000131      0.000197   
15          0.000361      0.000132      0.000219      0.000115      0.000206   
16          0.000170      0.000110      0.000212      0.000104      0.000223   
17          0.000184      0.000107      0.000265      0.000103      0.000211   
18          0.001372      0.000296      0.715186      0.001823      0.001504   
19          0.001240      0.000150      0.000408      0.000835      0.000342   
20          0.000253      0.000118      0.000216      0.000100      0.000198   
21          0.107550      0.000541      0.018105      0.004220      0.002672   
22          0.000187      0.000114      0.000255      0.000118      0.000210   
23          0.086474      0.000202      0.007469      0.000498      0.000860   
24          0.009312      0.855347      0.012240      0.017304      0.002821   
25          0.000317      0.000325      0.000455      0.000107      0.000208   
26          0.000944      0.000133      0.782414      0.000365      0.000734   
27          0.015222      0.002033      0.002371      0.000797      0.000492   
28          0.013573      0.000390      0.000390      0.943946      0.000448   
29          0.001596      0.000219      0.000440      0.000161      0.001545   
...              ...           ...           ...           ...           ...   
102247      0.011744      0.000159      0.000278      0.000262      0.000630   
102248      0.023782      0.001197      0.001665      0.000199      0.002497   
102249      0.016173      0.000173      0.000989      0.000440      0.001513   
102250      0.000947      0.990209      0.000296      0.004583      0.000767   
102251      0.000313      0.000124      0.000262      0.000116      0.000206   
102252      0.019426      0.000206      0.003041      0.002294      0.148614   
102253      0.042525      0.003856      0.000981      0.000288      0.000554   
102254      0.018590      0.890581      0.002887      0.019242      0.003334   
102255      0.023768      0.000369      0.037933      0.019112      0.002047   
102256      0.971047      0.000165      0.001957      0.000153      0.002503   
102257      0.000150      0.000104      0.000865      0.000116      0.000211   
102258      0.007068      0.001536      0.003288      0.001011      0.002143   
102259      0.000517      0.001032      0.022030      0.000266      0.000252   
102260      0.012343      0.000142      0.000934      0.004526      0.000842   
102261      0.014194      0.029313      0.040472      0.002672      0.002557   
102262      0.009359      0.884947      0.002183      0.059718      0.003388   
102263      0.006199      0.003063      0.003406      0.002360      0.003440   
102264      0.000405      0.000162      0.000362      0.000124      0.000200   
102265  

In [31]:
tesxxx

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0           0.377781      0.026681      0.026792      0.026730      0.027573   
1           0.036324      0.027207      0.317351      0.038313      0.026784   
2           0.070983      0.031819      0.034724      0.031946      0.031875   
3           0.026733      0.025957      0.026067      0.026282      0.025986   
4           0.032287      0.029314      0.029432      0.085062      0.029998   
5           0.033419      0.025812      0.027063      0.025862      0.025935   
6           0.411439      0.028920      0.037001      0.028519      0.031166   
7           0.027533      0.026681      0.027131      0.026682      0.026678   
8           0.026141      0.025302      0.025409      0.025351      0.025379   
9           0.056399      0.025455      0.027266      0.025456      0.025599   
10          0.025288      0.024979      0.025062      0.024979      0.025006   
11          0.030642      0.027654      0.027713      0.027881      0.027604   
12          0.024607      0.024433      0.024536      0.024480      0.024460   
13          0.028564      0.026536      0.026884      0.445978      0.027105   
14          0.028795      0.025432      0.025448      0.026163      0.025376   
15          0.162937      0.027738      0.029753      0.027892      0.028577   
16          0.025572      0.024834      0.024939      0.029646      0.024862   
17          0.027919      0.031365      0.025355      0.025014      0.025034   
18          0.038253      0.026386      0.026842      0.026437      0.026433   
19          0.026209      0.025033      0.025141      0.025079      0.025059   
20          0.032706      0.027468      0.027538      0.027422      0.053101   
21          0.024737      0.024421      0.024525      0.024533      0.024448   
22          0.146500      0.030819      0.031656      0.030723      0.030980   
23          0.035215      0.440901      0.026678      0.037144      0.026429   
24          0.072510      0.027292      0.026729      0.026701      0.027629   
25          0.081955      0.030620      0.030664      0.030594      0.030656   
26          0.032340      0.029515      0.030033      0.267847      0.029534   
27          0.040846      0.027593      0.027710      0.029387      0.027694   
28          0.031871      0.025326      0.025726      0.026340      0.025984   
29          0.026881      0.024672      0.024776      0.024720      0.025775   
...              ...           ...           ...           ...           ...   
102247      0.024576      0.024405      0.024506      0.024612      0.024430   
102248      0.024720      0.024521      0.024625      0.024569      0.024549   
102249      0.051257      0.026076      0.026374      0.026127      0.029677   
102250      0.024598      0.024661      0.024541      0.024471      0.024451   
102251      0.176991      0.030360      0.030458      0.029306      0.029346   
102252      0.025584      0.025124      0.025230      0.025172      0.025152   
102253      0.037054      0.028385      0.030193      0.029148      0.028471   
102254      0.025383      0.024730      0.035739      0.024778      0.024757   
102255      0.092980      0.030632      0.039300      0.030754      0.030770   
102256      0.033559      0.075564      0.025325      0.024208      0.024204   
102257      0.024891      0.024776      0.024937      0.554087      0.024742   
102258      0.029557      0.028841      0.245180      0.028951      0.028873   
102259      0.024726      0.024551      0.025625      0.024599      0.024578   
102260      0.024426      0.024230      0.024397      0.024277      0.024257   
102261      0.499551      0.025237      0.025382      0.025333      0.026043   
102262      0.024776      0.024578      0.024682      0.024625      0.024605   
102263      0.024670      0.024496      0.025460      0.024543      0.024537   
102264      0.039196      0.032444      0.031892      0.046614      0.032767   
102265  

In [32]:
train = pd.read_csv("../input/new_data/train_set.csv")
y=(train["class"]-1).astype(int)

In [33]:
del train

In [77]:
preds=np.argmax(other[lists].values,axis=1)

In [79]:
test_pred=pd.DataFrame(preds)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]+1).astype(int)

In [39]:
print ('score is {}'.format(f1_score(y, preds, average='macro')))

score is 0.8542490904191029


In [38]:
from sklearn.metrics import f1_score

In [81]:
test_pred["id"]=list(result2["id"])

In [94]:
test_pred[["id","class"]].to_csv('lgb_stacking.csv',index=None)

In [93]:
test_pred

class      id
0           5       0
1           4       1
2          13       2
3           4       3
4           5       4
5           5       5
6          15       6
7          19       7
8           3       8
9          12       9
10         10      10
11          1      11
12          5      12
13         13      13
14         15      14
15         18      15
16          9      16
17          9      17
18          3      18
19         14      19
20          9      20
21         11      21
22          9      22
23          9      23
24          2      24
25         15      25
26          3      26
27         15      27
28          4      28
29         19      29
...       ...     ...
102247     16  102247
102248      8  102248
102249     10  102249
102250      2  102250
102251     18  102251
102252     16  102252
102253     18  102253
102254      2  102254
102255     14  102255
102256      1  102256
102257      6  102257
102258     12  102258
102259     15  102259
102260     14  102260
102261     19  102261
102262      2  102262
102263     12  102263
102264     15  102264
102265     14  102265
102266     15  102266
102267      3  102267
102268      8  102268
102269     14  102269
102270      6  102270
102271     15  102271
102272      8  102272
102273      7  102273
102274      6  102274
102275     14  102275
102276     13  102276

[102277 rows x 2 columns]

In [85]:
other.shape

(102277, 19)

In [89]:
pred.shape

(102277, 19)