In [19]:
import pickle
import glob
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
import lightgbm as lgb

from sklearn.metrics import f1_score
# import time
# print('sleeping')
# time.sleep(7200)
# print('sleep done =======================')
# load feats
train_x,test_x = [],[]
for feat in sorted(glob.glob('../feature/stacking_pkl_file/*.pkl')):
    if 'fm2.pkl' in feat or 'ligbm' in  feat or '2leve' in  feat :
        continue
    print('file path',feat)
    a,b = pickle.load(open(feat,'rb'))
    print(a.shape,b.shape)
    train_x.append(a)
    test_x.append(b)
    
# train_x = np.nan_to_num(np.hstack(train_x))
# test_x = np.nan_to_num(np.hstack(test_x))
# print(train_x.shape)
    
# load y

# list_classes = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]
# train_y = train[list_classes].values.astype('int')
# print(train_x.shape)

file path ../feature/stacking_pkl_file/Capsule.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/capsule_all_shuffle.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/capsule_shuffle.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/cnn.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/dpcnn2000.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/mlp.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/mlp_shuffle.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/pseudo_rnn2.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/rnn2000.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/rnn7879.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/rnn_all_shuffle_all.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/rnn_cnn.pkl
(102277, 19) (102277, 19)
file path ../feature/stacking_pkl_file/rnn

In [20]:
for feat in sorted(glob.glob('../feature/other_features/features-vinson/*.csv')):
    if 'fm2.pkl' in feat or 'w2v' in feat or 'lda' in feat or 'lsi' in feat or 'xgb' in feat:
        continue
    print('file path',feat)
    file=pd.read_csv(feat)
    a = file.iloc[:102277,:]
    b = file.iloc[102277:,:]
    a = a.values
    b = b.values
    print(a.shape,b.shape)
    train_x.append(a)
    test_x.append(b)
train_x = np.nan_to_num(np.hstack(train_x))
test_x = np.nan_to_num(np.hstack(test_x))
print(train_x.shape)

file path ../feature/other_features/features-vinson/bnb_prob_10w.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/lr_prob.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/lr_prob_0.778620.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/mnb_prob_10w.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/nn_ensemble_0.775597.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/svc_prob.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/svc_prob_0.778881.csv
(102277, 19) (102277, 19)
file path ../feature/other_features/features-vinson/word_fasttext_0.760225.csv
(102277, 19) (102277, 19)
(102277, 437)


In [21]:
import pandas as pd
import numpy as np
train = pd.read_csv("../input/new_data/train_set.csv")
y=(train["class"]-1).astype(int)
del train
import gc
gc.collect()

458

In [22]:

from keras.utils import np_utils
train_y=np_utils.to_categorical(y,num_classes=19)

In [23]:
def self_f1_score(data, y_hat):
    y_true = data
    y_hat = np.round(y_hat) # scikits f1 doesn't like probabilities
    return f1_score(y_true, y_hat, average='macro')

def lgb_f1_score(y_hat, data):
    y_true = data.get_label()
    y_hat = np.round(y_hat) # scikits f1 doesn't like probabilities
    return 'f1', f1_score(y_true, y_hat, average='macro'), True

In [24]:
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import roc_auc_score
def simple_ens(model_name,k=3,rnd=233,lr=0.05,feature_fraction=0.9,bagging_fraction=0.9,
               bag_frec=3,met='binary_logloss'):
    kf = StratifiedKFold(n_splits=k, shuffle=True, random_state=rnd)
    test_pred, val_pred = np.zeros((102277,20)), np.zeros((102277,20))
    all_train_loss_l,all_val_loss_l = 0,0
    all_train_f1_l,all_val_f1_l = 0,0
    
    for i in range(19):
        val_loss_l,train_loss_l = 0,0
        val_f1_l,train_f1_l = 0,0
        fold_cnt = 0
        for train_index, test_index in kf.split(train_x,train_y[:,i]):
            # x,y
            curr_x,curr_y = train_x[train_index],train_y[train_index]
            hold_out_x,hold_out_y = train_x[test_index],train_y[test_index]
            d_test = test_x
            # share params
            params = {
                    'application': 'binary',
                    'num_leaves': 15,
                    #'lambda_l1': 1,
                    'lambda_l2': 1.0,
                    'max_depth': 4,
                    #'scale_pos_weight':0.9,
                    'metric': met, # or auc
                    'data_random_seed': 2,
                    'learning_rate':lr,
                    'bagging_fraction': bagging_fraction,
                    'bagging_freq':bag_frec,
                    'feature_fraction': feature_fraction,
                    'num_threads':4

                    }
            if met == 'auc':
                s_round = 100
            else:
                s_round = 50
            # train for each class
            d_train = lgb.Dataset(curr_x, curr_y[:,i])
            d_valid = lgb.Dataset(hold_out_x, hold_out_y[:,i])
            watchlist = [d_train, d_valid]
            model = lgb.train(params,
#                       feval=lgb_f1_score,
                      train_set=d_train,
                      num_boost_round=2000,
                      valid_sets=watchlist,
                      early_stopping_rounds=100,
                      verbose_eval=None)
            print(fold_cnt,'fold: ',end='')
            fold_cnt += 1
            train_pred = model.predict(curr_x)
            val_pred[test_index, i] = model.predict(hold_out_x)
            curr_train_loss = log_loss(curr_y[:,i],train_pred)
            curr_val_loss = log_loss(hold_out_y[:,i],val_pred[test_index, i])

            curr_train_f1 = self_f1_score(curr_y[:,i],train_pred)
            curr_val_f1 = self_f1_score(hold_out_y[:,i],val_pred[test_index, i])

            print('ls',curr_train_loss,curr_val_loss,'f1',curr_train_f1,curr_val_f1)
            val_loss_l += curr_val_loss
            train_loss_l += curr_train_loss
            val_f1_l += curr_val_f1
            train_f1_l += curr_train_f1
            curr_test_pred = model.predict(d_test)
            test_pred[:,i] += curr_test_pred
            
        # avg k fold
        train_loss_l = train_loss_l/k
        val_loss_l = val_loss_l/k
        train_f1_l = train_f1_l/k
        val_f1_l = val_f1_l/k
        print('this class avg train',train_loss_l,'avg val',val_loss_l)
        print('this class f1 train',train_f1_l,'f1 val',val_f1_l)
        
        
        # avg 6 class
        all_train_loss_l += train_loss_l/19
        all_val_loss_l += val_loss_l/19
        all_train_f1_l += train_f1_l/19
        all_val_f1_l += val_f1_l/19
        print('========================')
    test_pred = test_pred/k
    print('all loss avg',all_train_loss_l,all_val_loss_l)
    print('all f1 avg',all_train_f1_l,all_val_f1_l)
    print('=======================================================')
    return val_pred, test_pred

print('done')

done


In [25]:

lgb_train, lgb_res = simple_ens('lgb',5,233,0.05,0.6)
##all loss avg 0.04941417146346469 0.05321999547256359
# all f1 avg 0.8965591064486441 0.8915637951017253
#######################7982<lb<7985

#all loss avg 0.04911572582626101 0.052974216091397554
# all f1 avg 0.8970629823676124 0.8922944850147942

# all loss avg 0.0414203008656468 0.052978859434622785
# all f1 avg 0.9103949564755508 0.8924077581728779

# all loss avg 0.04539159633943475 0.05255053671449584
# all f1 avg 0.9029697229659733 0.8934845973558836

#all loss avg 0.04494700768702617 0.052254864071516055
# all f1 avg 0.9040207644649525 0.8939220820764944

# all loss avg 0.04353723194221981 0.051953447288746665
# all f1 avg 0.9064007590628727 0.8947753048612783
# 7940810057586943

# all loss avg 0.041791878911084705 0.0502085007027876
# all f1 avg 0.9094424575179055 0.8970108064794169
#0.7956058839820572
#0.8979044788487316

/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py:186: UserWarning: Usage subset(sliced data) of np.ndarray is not recommended due to it will double the peak memory cost in LightGBM.
  warnings.warn("Usage subset(sliced data) of np.ndarray is not recommended due to it will double the peak memory cost in LightGBM.")


0 fold: ls 0.08827563701288117 0.09553616387429105 f1 0.8043222755634124 0.7994799611204153
1 fold: ls 0.08657027530838257 0.09877635784900357 f1 0.8067430705685795 0.7896281263712155
2 fold: ls 0.08881709534546858 0.09729638105085076 f1 0.8049214364250823 0.8037576017451533
3 fold: ls 0.08017932511270662 0.09831054426410638 f1 0.8204449311485509 0.7942332855894818
4 fold: ls 0.07941667528772789 0.0975385637618827 f1 0.8196513936465029 0.7943812764818012
this class avg train 0.08465180161343337 avg val 0.09749160216002689
this class f1 train 0.8112166214704256 f1 val 0.7962960502616134
0 fold: ls 0.024078599889330036 0.028995300020772382 f1 0.9138724808527812 0.9035573194311969
1 fold: ls 0.0218544243459654 0.03236329900675408 f1 0.9186785020445116 0.8936851796734968
2 fold: ls 0.023874336909500783 0.029480033848739182 f1 0.9154258963494506 0.9042401162149432
3 fold: ls 0.022012829601353045 0.03255242649172084 f1 0.9191003363656742 0.8932971667559146
4 fold: ls 0.02359262807802929 0.03

2 fold: ls 0.04936849461141498 0.0594056258789206 f1 0.9188920908357143 0.8999406558669256
3 fold: ls 0.049601417257087804 0.060595329909789546 f1 0.918950635457121 0.9043372428641226
4 fold: ls 0.04819868363151262 0.06091689271508531 f1 0.9185476624366806 0.9083890166922003
this class avg train 0.04870699962802454 avg val 0.0590846736383551
this class f1 train 0.9192765987623558 f1 val 0.9063863854144962
0 fold: ls 0.025842413181468883 0.031953902163249795 f1 0.9652093361930522 0.9604460777317545
1 fold: ls 0.02514372216349045 0.0314766734781418 f1 0.9669257643847755 0.9599539282346058
2 fold: ls 0.025990628438587637 0.03659816193842366 f1 0.9658653113943834 0.9532230104503185
3 fold: ls 0.02650726287590244 0.03511565768984758 f1 0.9652708198303492 0.9620627565069513
4 fold: ls 0.027157055141466154 0.03455296424411928 f1 0.9644849470857366 0.9584981762462647
this class avg train 0.02612821636018311 avg val 0.033939471902756424
this class f1 train 0.9655512357776594 f1 val 0.9588367898

In [26]:
with open('../feature/2leve_lgb_stacking8.pkl','wb') as fout:
    pickle.dump([lgb_train,lgb_res],fout)

In [27]:
test_dir = '../input/new_data/test_set.csv'
test = pd.read_csv(test_dir)
test_id = test[["id"]].copy()

In [28]:
preds=np.argmax(lgb_res,axis=1)
test_pred=pd.DataFrame(preds)
test_pred.columns=["class"]
test_pred["class"]=(test_pred["class"]+1).astype(int)
print(test_pred.shape)
print(test_id.shape)
test_pred["id"]=list(test_id["id"])
test_pred[["id","class"]].to_csv('../output/lgbstacknnx3.csv',index=None)

(102277, 1)
(102277, 1)


In [29]:
preds

array([ 5,  4, 13, ...,  6, 14, 13])

In [30]:
name = ["class_prob_%s"%i for i in range(1,21)]
df_lgb = pd.DataFrame(lgb_res, columns=name)
df_lgb = df_lgb.drop('class_prob_20', axis=1)

In [31]:

df_lgb.to_csv('../pro/stacking_lgbx3.csv', index=False)

In [32]:
df_lgb

class_prob_1  class_prob_2  class_prob_3  class_prob_4  class_prob_5  \
0           0.002243      0.000325      0.000705      0.003167      0.989950   
1           0.002102      0.000295      0.000464      0.990493      0.000269   
2           0.048086      0.003451      0.090661      0.002261      0.016101   
3           0.000416      0.000195      0.000306      0.993631      0.000303   
4           0.007421      0.000248      0.001962      0.003248      0.957149   
5           0.042360      0.004619      0.004972      0.000883      0.905513   
6           0.022126      0.001004      0.004279      0.004812      0.000478   
7           0.027287      0.150816      0.002845      0.001222      0.003192   
8           0.000297      0.000154      0.993834      0.000148      0.000278   
9           0.116432      0.002801      0.001755      0.002846      0.002998   
10          0.052592      0.000771      0.000533      0.000585      0.001660   
11          0.309132      0.317520      0.005020      0.001153      0.014201   
12          0.003322      0.000826      0.000428      0.000234      0.980133   
13          0.015126      0.000443      0.001608      0.001519      0.000614   
14          0.000265      0.000165      0.000228      0.000167      0.000260   
15          0.000553      0.000188      0.000236      0.000139      0.000265   
16          0.000238      0.000165      0.000261      0.000140      0.000289   
17          0.000260      0.000161      0.000302      0.000141      0.000266   
18          0.001547      0.000368      0.677820      0.002328      0.001408   
19          0.001293      0.000218      0.000381      0.000876      0.000364   
20          0.000417      0.000172      0.000230      0.000139      0.000253   
21          0.108066      0.000490      0.018776      0.004094      0.002564   
22          0.000271      0.000174      0.000264      0.000144      0.000271   
23          0.089409      0.000276      0.007051      0.000527      0.000953   
24          0.009711      0.865489      0.013792      0.018470      0.003272   
25          0.000384      0.000425      0.000389      0.000149      0.000275   
26          0.000856      0.000187      0.695518      0.000385      0.000926   
27          0.014762      0.001428      0.002216      0.000881      0.000532   
28          0.013703      0.000446      0.000508      0.943848      0.000437   
29          0.001529      0.000302      0.000446      0.000196      0.002862   
...              ...           ...           ...           ...           ...   
102247      0.010127      0.000246      0.000273      0.000270      0.000971   
102248      0.020077      0.001054      0.001206      0.000297      0.002634   
102249      0.016704      0.000249      0.000912      0.000377      0.001916   
102250      0.001013      0.988637      0.000397      0.003444      0.001112   
102251      0.000570      0.000177      0.000284      0.000162      0.000268   
102252      0.021049      0.000305      0.002783      0.001736      0.153063   
102253      0.042093      0.003008      0.000773      0.000267      0.000558   
102254      0.018986      0.904875      0.002518      0.015787      0.004009   
102255      0.022291      0.000417      0.042479      0.019155      0.001915   
102256      0.962063      0.000237      0.002032      0.000181      0.002603   
102257      0.000264      0.000162      0.000739      0.000158      0.000278   
102258      0.007410      0.001595      0.002587      0.000990      0.001886   
102259      0.000543      0.001200      0.026564      0.000273      0.000318   
102260      0.013300      0.000215      0.000594      0.004241      0.000798   
102261      0.014231      0.025711      0.034120      0.002825      0.002644   
102262      0.010385      0.867443      0.002077      0.065033      0.004223   
102263      0.007094      0.003920      0.003612      0.003088      0.002837   
102264      0.000439      0.000222      0.000371      0.000207      0.000264   
102265  

In [8]:
a[0]

array([0.63021084, 0.00073022, 0.12938255, 0.08233588, 0.38772137,
       0.35054736, 0.06010154, 0.0162588 , 0.35044424, 0.36899349,
       0.33343102, 0.00718196, 0.00099249, 0.13392986, 0.03079003,
       0.40782321, 0.38772949, 0.11120969, 0.07217844, 0.        ])

In [17]:
b[0]

array([0.10306741, 0.21446534, 0.09234781, 0.1665037 , 0.77700784,
       0.20140753, 0.09591953, 0.09388762, 0.21980566, 0.2528162 ,
       0.18957717, 0.15716459, 0.16162135, 0.08285841, 0.18494502,
       0.15308998, 0.16854106, 0.1316501 , 0.07221129])

In [13]:
a = np.delete(a, -1, axis=1)

In [12]:
a, b= pickle.load(open('../feature/stacking_pkl_file/2leve_lgb_stacking3.pkl','rb'))

In [12]:
b = pickle.load(open('../feature/stacking_pkl_file/rnn_model_bagging2.pkl','rb'))

In [5]:
a.shape

(102277, 20)

In [18]:
with open('../feature/2leve_lgb_stacking3.pkl','wb') as fout:
    pickle.dump([a,b],fout)

In [26]:
c.shape

(102277, 19)

In [29]:
c[0]

array([6.01716689e-04, 6.16839170e-05, 7.57186936e-05, 1.06231030e-03,
       9.96983826e-01, 3.12459830e-04, 6.37228004e-05, 1.02987576e-06,
       2.93245284e-05, 1.16468422e-04, 1.56775292e-04, 3.49557318e-04,
       1.02049326e-05, 3.78012592e-05, 1.93889423e-06, 1.43233101e-05,
       1.13495912e-06, 1.05727275e-04, 1.42806357e-05], dtype=float32)

In [ ]:
a=[1,2]

In [11]:
lgb_res[1]

array([7.51418984e-04, 8.59006145e-05, 5.72015080e-05, 9.98149313e-01,
       2.16004989e-05, 2.21425307e-05, 1.92076409e-05, 2.88491225e-05,
       4.80360194e-05, 6.77559877e-05, 1.46532588e-04, 8.52455299e-05,
       1.89921750e-05, 8.53312692e-06, 1.33990754e-05, 7.04179440e-06,
       1.30948036e-05, 1.99016595e-05, 7.09543232e-05, 0.00000000e+00])